services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: taskflow
      POSTGRES_USER: admin
    ports:
      - "5432:5432"
    volumes:
      - taskflow_postgres_data:/var/lib/postgresql/data

volumes:
  taskflow_postgres_data:
